version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Preparing build..."

  build:
    commands:
      - echo "Packaging website..."
      - zip -r website.zip Website

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - website.zip
